### ISSUE TITLE
PEP 8 style guide

### ISSUE THREAD

**Issue by cwrowley** [wcs211/BEM-2D-Python#2]
It would be good to follow the style conventions in [PEP 8](https://www.python.org/dev/peps/pep-0008/).  These are very widely followed by the Python community, and while it seems nit-picky, following these conventions actually makes it much easier to read and understand each other's code.

It's also worth taking a look at the [Google Python Style Guide](https://google-styleguide.googlecode.com/svn/trunk/pyguide.html).

**Comment by gas213** [comment]
Hi Dr. Rowley,
Thank you again for taking the time to meet with us! I have adopted the PEP 8 formatting, and am now reading through your APC 524 notes in addition to other resources to learn more about class structure.
